config/routes.rb
Rails.application.routes.draw do
  resources :file_uploads
  root to: "file_uploads#index"
  devise_for :users,
             path: "",
             path_names: { sign_in: "login", sign_out: "logout", edit: "profile", sign_up: "registration" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/file_upload.rb
class FileUpload < ApplicationRecord
  belongs_to :user
  has_one_attached :file

  validates :title, presence: true
  validates :file, attached: true, size: {less_than: 1.gigabyte, message: "size should not be greater than 1 Gb"}
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/file_uploads_controller.rb
class FileUploadsController < ApplicationController
  before_action :set_file_upload, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @file_uploads = FileUpload.where(user_id: current_user)
  end

  def show
    @file_upload = FileUpload.find(params[:id])
    @tiny_url = ShortURL.shorten(url_for(@file_upload.file))
  end

  def new
    @file_upload = FileUpload.new
  end

  def edit
  end

  def create
    @file_upload = FileUpload.new(file_upload_params)

    respond_to do |format|
      if @file_upload.save
        format.html { redirect_to @file_upload, notice: "File upload was successfully created." }
        format.json { render :show, status: :created, location: @file_upload }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @file_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @file_upload.update(file_upload_params)
        format.html { redirect_to @file_upload, notice: "File upload was successfully updated." }
        format.json { render :show, status: :ok, location: @file_upload }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @file_upload.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @file_upload.destroy

    respond_to do |format|
      format.html { redirect_to file_uploads_path, status: :see_other, notice: "File upload was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_file_upload
      @file_upload = FileUpload.find(params[:id])
    end

    def file_upload_params
      params.require(:file_upload).permit(:title, :description, :user_id, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_uploads_helper.rb
module FileUploadsHelper
end

app/views/file_uploads/_form.html.erb
<%= form_with(model: file_upload) do |form| %>
  <% if file_upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(file_upload.errors.count, "error") %> prohibited this file_upload from being saved:</h2>

      <ul>
        <% file_upload.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field" style="display: none;">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file, id: 'file_input' %>
  </div>

  <div class="actions">
    <%= form.submit "Save"%>
  </div>
<% end %>

app/views/file_uploads/edit.html.erb
<h1>Editing File Upload</h1>

<%= render 'form', file_upload: @file_upload %>

<%= link_to 'Show', @file_upload %> |
<%= link_to 'Back', file_uploads_path %>

app/views/file_uploads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>File Uploads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @file_uploads.each do |file_upload| %>
      <tr>
        <td><%= file_upload.title %></td>
        <td><%= file_upload.description %></td>
        <td><%= link_to 'Show', file_upload %></td>
        <td><%= link_to 'Edit', edit_file_upload_path(file_upload) %></td>
        <td><%= link_to 'Destroy', file_upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File Upload', new_file_upload_path %>
<%= link_to 'Logout', destroy_user_session_path, method: :delete %>

app/views/file_uploads/new.html.erb
<h1>New File Upload</h1>

<%= render 'form', file_upload: @file_upload %>

<%= link_to 'Back', file_uploads_path %>

app/views/file_uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @file_upload.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @file_upload.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @file_upload.user_id %>
</p>

<% if @file_upload.file.attached? %>
  <p>
    <strong>File:</strong>
    <%= link_to 'Download File', rails_blob_path(@file_upload.file, disposition: 'attachment') %>
  </p>
<% end %>

<p>
  <strong>Link to Share URL:</strong>
  <%= @tiny_url %>
</p>

<%= link_to 'Edit', edit_file_upload_path(@file_upload) %> |
<%= link_to 'Back', file_uploads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>